language: android
sudo: required
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

env:
  global:
  - ANDROID_API=24
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=24.0.2
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-m2repository
  - extra-android-m2repository # for design library
  - addon-google_apis-google-19 # google play services
  - sys-img-armeabi-v7a-google_apis-23$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-google_apis-23$EMULATOR_API_LEVEL

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
#- ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"

before_script:
- echo no | android create avd --force -n test -t android-21 --abi $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
